### ISSUE TITLE
Release flow-networking on Maven Central

### ISSUE THREAD

**Issue by deathcap** [flow/network#11]
Could this library be published on Maven Central? Other com.flowpowered projects are:

http://mvnrepository.com/artifact/com.flowpowered

but not flow-networking. It has stabilized and is used by https://github.com/GlowstonePlusPlus/GlowstonePlusPlus (and https://github.com/GlowstoneMC/Glowstone), but both are currently using the 1.1.0-SNAPSHOT version as that's all that's available. Would be convenient if there was a full release, to avoid relying on snapshot versions (since snapshots are meant for frequently-changing dependencies, they are refreshed regularly, retrieved from other sources, etc. but com.flowpowered.flow-networking is stable in its current state.)

@kitskub

**Comment by lukespragg** [comment]
I'll push a release for it soon, but it'll be under flow-network most likely.

**Comment by lukespragg** [comment]
Sorry for the delay! This has been done. Make sure to check the commits for the changes made in order to be able to use it.
